[package]
name = "worker"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.101"
dotenvy = "0.15.7"
shared = { version = "0.1.0", path = "../shared" }
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
